### ISSUE TITLE
Images and tasks cannot be re-uploaded/re-run

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen-web-app#107]
An image cannot be uploaded twice. Same thing for running a task. This becomes a problem when the user decides to remove an image or remove a report from the screen. If later on the user decides to re-upload the image, this will not show up amongst the files, or if the user decides to re-run the same task on the image, this will not show on the reports page.

**Comment by tomaroberts** [comment]
Thanks for flagging Lu – this is an important one. I will assign you to investigate further.

**Comment by tomaroberts** [comment]
@sophie22 – thoughts on this one? We have a delete button; I'm not sure whether that gets around this issue, or whether you still can't re-upload a dataset even if the delete button has been used. I'm not sure how far the delete button extends, i.e.: does it remove just the files froms the `uploads` dir and leave the database entries?

Could you investigate the behaviour around this issue a bit more please? Thanks.

**Comment by sophie22** [comment]
file upload, delete, reupload is fixed by #118  ✅ 
rerunning task on the same series currently doesn't trigger a Celery task, but the result from the previous identical task is available - will have to modify current display logic in the future when optional task variables may be changes, leading to different results.
